using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RotMG_Net_Lib.Networking.Packets
{

    public enum PacketType : byte
    {
        Failure = 0,
        CreateSuccess = 44,
        Create = 52,
        PlayerShoot = 8,
        Move = 74,
        PlayerText = 59,
        Text = 20,
        ServerPlayerShoot = 5,
        Damage = 58,
        Update = 31,
        UpdateAck = 80,
        Notification = 47,
        NewTick = 36,
        InvSwap = 27,
        UseItem = 39,
        ShowEffect = 28,
        Hello = 85,
        Goto = 76,
        InvDrop = 46,
        InvResult = 82,
        Reconnect = 12,
        Ping = 4,
        Pong = 86,
        MapInfo = 100,
        Load = 62,
        Pic = 50,
        SetCondition = 19,
        Teleport = 99,
        UsePortal = 91,
        Death = 104,
        Buy = 68,
        BuyResult = 87,
        Aoe = 68,
        GroundDamage = 84,
        PlayerHit = 67,
        EnemyHit = 96,
        AoeAck = 102,
        ShootAck = 3,
        OtherHit = 25,
        SquareHit = 95,
        GotoAck = 81,
        EditAccountList = 21,
        AccountList = 1,
        QuestObjId = 7,
        ChooseName = 9,
        NameResult = 13,
        CreateGuild = 40,
        GuildResult = 65,
        GuildRemove = 101,
        GuildInvite = 75,
        AllyShoot = 63,
        EnemyShoot = 92,
        RequestTrade = 6,
        TradeRequested = 14,
        TradeStart = 15,
        ChangeTrade = 26,
        TradeChanged = 93,
        AcceptTrade = 17,
        CancelTrade = 55,
        TradeDone = 77,
        TradeAccepted = 57,
        ClientStat = 66,
        CheckCredits = 35,
        Escape = 41,
        File = 42,
        InvitedToGuild = 83,
        JoinGuild = 94,
        ChangeGuildRank = 51,
        PlaySound = 61,
        GlobalNotification = 90,
        Reskin = 69,
        PetUpgradeRequest = 11,
        ActivePetUpdateRequest = 53,
        ActivePetUpdate = 56,
        NewAbility = 60,
        PetYardUpdate = 38,
        EvolvePet = 97,
        DeletePet = 78,
        HatchPet = 22,
        EnterArena = 89,
        ImminentArenaWave = 23,
        ArenaDeath = 34,
        AcceptArenaDeath = 10,
        VerifyEmail = 49,
        ReskinUnlock = 98,
        PasswordPrompt = 48,
        QuestFetchAsk = 16,
        QuestRedeem = 24,
        QuestFetchResponse = 79,
        QuestRedeemResponse = 30,
        PetChangeFormMsg = 64,
        KeyInfoRequest = 45,
        KeyInfoResponse = 33,
        ClaimLoginRewardMsg = 103,
        LoginRewardMsg = 37,
        QuestRoomMsg = 88,
        PetChangeSkinMsg = 105,
        RealmHeroLeftMsg = 111,
        ChatHelloMsg = 106,
        ChatTokenMsg = 107,
        ChatLogoutMsg = 108
    }
}
